-- Database schema dump (DDL only) generated by dump_db.py

-- ---- alembic_version ----
CREATE TABLE `alembic_version` (
  `version_num` varchar(32) NOT NULL,
  PRIMARY KEY (`version_num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- metadata_entries ----
CREATE TABLE `metadata_entries` (
  `id` int NOT NULL AUTO_INCREMENT,
  `table_name` varchar(255) NOT NULL,
  `column_name` varchar(255) DEFAULT NULL,
  `module_name` varchar(255) DEFAULT NULL,
  `description` text,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_metadata_entry` (`table_name`,`column_name`,`module_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_audit ----
CREATE TABLE `rb_audit` (
  `audit_id` bigint NOT NULL AUTO_INCREMENT,
  `event_id` varchar(36) NOT NULL,
  `tblname` varchar(64) NOT NULL,
  `row_id` bigint NOT NULL,
  `audit_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `action` enum('add','invite','register','login','edit','grant_module','revoke_module') NOT NULL,
  `actor_id` bigint DEFAULT NULL,
  `source` enum('self','admin','api') NOT NULL DEFAULT 'api',
  `prev_data` json DEFAULT NULL,
  `new_data` json DEFAULT NULL,
  PRIMARY KEY (`audit_id`),
  KEY `ix_rb_audit_event_id` (`event_id`)
) ENGINE=InnoDB AUTO_INCREMENT=98 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_chat_message ----
CREATE TABLE `rb_chat_message` (
  `message_id` bigint NOT NULL AUTO_INCREMENT,
  `thread_id` bigint NOT NULL,
  `sender_id` bigint NOT NULL,
  `body` text NOT NULL,
  `reply_to_message_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`message_id`),
  KEY `ix_chat_msg_thread_created` (`thread_id`,`created_at`),
  KEY `ix_chat_msg_sender` (`sender_id`),
  KEY `idx_chat_msg_reply_to` (`reply_to_message_id`),
  CONSTRAINT `fk_chat_msg_reply` FOREIGN KEY (`reply_to_message_id`) REFERENCES `rb_chat_message` (`message_id`) ON DELETE SET NULL,
  CONSTRAINT `fk_chat_msg_sender` FOREIGN KEY (`sender_id`) REFERENCES `rb_user` (`user_id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_chat_msg_thread` FOREIGN KEY (`thread_id`) REFERENCES `rb_chat_thread` (`thread_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=67 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_chat_message_reaction ----
CREATE TABLE `rb_chat_message_reaction` (
  `reaction_id` bigint NOT NULL AUTO_INCREMENT,
  `message_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `emoji` varchar(32) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`reaction_id`),
  UNIQUE KEY `uq_chat_message_reaction` (`message_id`,`user_id`),
  KEY `ix_chat_reaction_message` (`message_id`),
  KEY `ix_chat_reaction_user` (`user_id`),
  CONSTRAINT `fk_chat_reaction_message` FOREIGN KEY (`message_id`) REFERENCES `rb_chat_message` (`message_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_chat_reaction_user` FOREIGN KEY (`user_id`) REFERENCES `rb_user` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_chat_thread ----
CREATE TABLE `rb_chat_thread` (
  `thread_id` bigint NOT NULL AUTO_INCREMENT,
  `thread_type` enum('dm','group','broadcast') NOT NULL DEFAULT 'dm',
  `name` varchar(120) DEFAULT NULL,
  `created_by` bigint NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`thread_id`),
  KEY `ix_chat_thread_type` (`thread_type`),
  KEY `ix_chat_thread_updated` (`updated_at`),
  KEY `fk_chat_thread_created_by` (`created_by`),
  CONSTRAINT `fk_chat_thread_created_by` FOREIGN KEY (`created_by`) REFERENCES `rb_user` (`user_id`) ON DELETE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_chat_thread_member ----
CREATE TABLE `rb_chat_thread_member` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `thread_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `role` enum('owner','member') NOT NULL DEFAULT 'member',
  `joined_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_read_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_chat_thread_member` (`thread_id`,`user_id`),
  KEY `ix_chat_member_user` (`user_id`),
  KEY `ix_chat_member_thread` (`thread_id`),
  CONSTRAINT `fk_chat_member_thread` FOREIGN KEY (`thread_id`) REFERENCES `rb_chat_thread` (`thread_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_chat_member_user` FOREIGN KEY (`user_id`) REFERENCES `rb_user` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_cv_pair ----
CREATE TABLE `rb_cv_pair` (
  `cv_id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `v_name` varchar(120) NOT NULL DEFAULT '',
  `v_company` varchar(120) NOT NULL DEFAULT '',
  `v_email` varchar(120) NOT NULL DEFAULT '',
  `v_phone` varchar(50) NOT NULL DEFAULT '',
  `v_primary_skill` varchar(120) NOT NULL DEFAULT '',
  `v_skill_description` text NOT NULL,
  `v_organizations` varchar(255) NOT NULL DEFAULT '',
  `v_achievements` varchar(255) NOT NULL DEFAULT '',
  `op_name` varchar(120) NOT NULL DEFAULT '',
  `op_email` varchar(120) NOT NULL DEFAULT '',
  `op_phone` varchar(50) NOT NULL DEFAULT '',
  `op_title` varchar(150) NOT NULL DEFAULT '',
  `op_linkedin_url` varchar(255) NOT NULL DEFAULT '',
  `op_website_url` varchar(255) NOT NULL DEFAULT '',
  `op_about` text NOT NULL,
  `op_skills` text NOT NULL,
  `op_experience` text NOT NULL,
  `op_academic` text NOT NULL,
  `op_achievements` text NOT NULL,
  `op_final_remark` text NOT NULL,
  `onepage_html` text NOT NULL,
  `is_archived` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`cv_id`),
  KEY `idx_cv_user` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_cv_profile ----
CREATE TABLE `rb_cv_profile` (
  `profile_id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `doc_type` varchar(20) NOT NULL,
  `details` json NOT NULL,
  `pdf_data` longblob,
  `pdf_name` varchar(255) DEFAULT NULL,
  `pdf_mime` varchar(120) DEFAULT NULL,
  `pdf_size` bigint DEFAULT NULL,
  `cover_pdf_data` longblob,
  `cover_pdf_name` varchar(255) DEFAULT NULL,
  `cover_pdf_mime` varchar(120) DEFAULT NULL,
  `cover_pdf_size` bigint DEFAULT NULL,
  `is_archived` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`profile_id`),
  KEY `idx_cv_profile_user` (`user_id`),
  KEY `idx_cv_profile_user_type` (`user_id`,`doc_type`)
) ENGINE=InnoDB AUTO_INCREMENT=1000000005 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_cv_public_link ----
CREATE TABLE `rb_cv_public_link` (
  `link_id` bigint NOT NULL AUTO_INCREMENT,
  `cvfile_id` bigint NOT NULL,
  `created_by` bigint NOT NULL,
  `share_type` enum('public','user','email') NOT NULL DEFAULT 'public',
  `target` varchar(320) DEFAULT NULL,
  `name` varchar(150) DEFAULT NULL,
  `token` varchar(64) NOT NULL,
  `allow_download` tinyint(1) NOT NULL DEFAULT '0',
  `password_hash` varchar(255) DEFAULT NULL,
  `status` enum('active','disabled') NOT NULL DEFAULT 'active',
  `expires_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`link_id`),
  UNIQUE KEY `uq_cv_public_token` (`token`),
  KEY `idx_cv_public_cv` (`cvfile_id`),
  KEY `idx_cv_public_creator` (`created_by`),
  CONSTRAINT `fk_cv_public_profile` FOREIGN KEY (`cvfile_id`) REFERENCES `rb_cv_profile` (`profile_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_cv_share ----
CREATE TABLE `rb_cv_share` (
  `share_id` bigint NOT NULL AUTO_INCREMENT,
  `cv_id` bigint NOT NULL,
  `owner_user_id` bigint NOT NULL,
  `target_user_id` bigint DEFAULT NULL,
  `target_email` varchar(200) DEFAULT NULL,
  `share_token` varchar(64) NOT NULL,
  `is_public` tinyint(1) NOT NULL DEFAULT '0',
  `is_archived` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`share_id`),
  UNIQUE KEY `uk_share_token` (`share_token`),
  KEY `idx_share_cv` (`cv_id`),
  KEY `idx_share_owner` (`owner_user_id`),
  KEY `idx_share_target_user` (`target_user_id`),
  KEY `idx_share_target_email` (`target_email`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_cvfile_share ----
CREATE TABLE `rb_cvfile_share` (
  `share_id` bigint NOT NULL AUTO_INCREMENT,
  `cvfile_id` bigint NOT NULL,
  `owner_user_id` bigint NOT NULL,
  `target_user_id` bigint DEFAULT NULL,
  `target_email` varchar(200) DEFAULT NULL,
  `share_token` varchar(64) NOT NULL,
  `is_public` tinyint(1) NOT NULL DEFAULT '0',
  `is_archived` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`share_id`),
  UNIQUE KEY `uq_rb_cvfile_share_token` (`share_token`),
  KEY `idx_rb_cvfile_share_cvfile` (`cvfile_id`),
  KEY `idx_rb_cvfile_share_owner` (`owner_user_id`),
  KEY `idx_rb_cvfile_share_target_user` (`target_user_id`),
  KEY `idx_rb_cvfile_share_target_email` (`target_email`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_invitation ----
CREATE TABLE `rb_invitation` (
  `invitation_id` bigint NOT NULL AUTO_INCREMENT,
  `email` varchar(320) NOT NULL,
  `token` varchar(255) NOT NULL,
  `expires_at` datetime NOT NULL,
  `used` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`invitation_id`),
  UNIQUE KEY `uq_invite_token` (`token`),
  KEY `ix_invite_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_module ----
CREATE TABLE `rb_module` (
  `module_key` varchar(50) NOT NULL,
  `name` varchar(120) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `is_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`module_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_password_reset ----
CREATE TABLE `rb_password_reset` (
  `reset_id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `token` varchar(255) NOT NULL,
  `expires_at` datetime NOT NULL,
  `used` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`reset_id`),
  UNIQUE KEY `uq_reset_token` (`token`),
  KEY `fk_reset_user` (`user_id`),
  CONSTRAINT `fk_reset_user` FOREIGN KEY (`user_id`) REFERENCES `rb_user` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_schema_migrations ----
CREATE TABLE `rb_schema_migrations` (
  `filename` varchar(255) NOT NULL,
  `applied_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`filename`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_social_like ----
CREATE TABLE `rb_social_like` (
  `like_id` bigint NOT NULL AUTO_INCREMENT,
  `post_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`like_id`),
  UNIQUE KEY `uq_social_like` (`post_id`,`user_id`),
  KEY `idx_social_like_post` (`post_id`),
  KEY `idx_social_like_user` (`user_id`),
  CONSTRAINT `fk_social_like_post` FOREIGN KEY (`post_id`) REFERENCES `rb_social_post` (`post_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_social_like_user` FOREIGN KEY (`user_id`) REFERENCES `rb_user` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_social_post ----
CREATE TABLE `rb_social_post` (
  `post_id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `parent_id` bigint DEFAULT NULL,
  `body` text NOT NULL,
  `image_path` varchar(500) DEFAULT NULL,
  `cvfile_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`post_id`),
  KEY `ix_social_user` (`user_id`),
  KEY `ix_social_parent` (`parent_id`),
  KEY `ix_social_root` (`parent_id`,`created_at`),
  KEY `ix_social_cvfile` (`cvfile_id`),
  CONSTRAINT `fk_social_parent` FOREIGN KEY (`parent_id`) REFERENCES `rb_social_post` (`post_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_social_user` FOREIGN KEY (`user_id`) REFERENCES `rb_user` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_user ----
CREATE TABLE `rb_user` (
  `user_id` bigint NOT NULL AUTO_INCREMENT,
  `email` varchar(320) NOT NULL,
  `password_hash` varchar(255) DEFAULT NULL,
  `status` enum('invited','active','blocked','deleted') NOT NULL DEFAULT 'invited',
  `is_admin` tinyint(1) NOT NULL DEFAULT '0',
  `invited_at` datetime DEFAULT NULL,
  `invited_by` bigint DEFAULT NULL,
  `registered_at` datetime DEFAULT NULL,
  `last_login_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `uq_rb_user_email` (`email`),
  KEY `ix_rb_user_email` (`email`),
  KEY `ix_rb_user_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_user_module ----
CREATE TABLE `rb_user_module` (
  `user_id` bigint NOT NULL,
  `module_key` varchar(50) NOT NULL,
  `has_access` tinyint(1) NOT NULL DEFAULT '1',
  `granted_by` bigint DEFAULT NULL,
  `granted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`,`module_key`),
  KEY `fk_um_module` (`module_key`),
  CONSTRAINT `fk_um_module` FOREIGN KEY (`module_key`) REFERENCES `rb_module` (`module_key`) ON DELETE CASCADE,
  CONSTRAINT `fk_um_user` FOREIGN KEY (`user_id`) REFERENCES `rb_user` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_user_profile ----
CREATE TABLE `rb_user_profile` (
  `user_id` bigint NOT NULL,
  `handle` varchar(64) DEFAULT NULL,
  `rgDisplay` varchar(200) NOT NULL,
  `full_name` varchar(200) DEFAULT NULL,
  `display_name` varchar(120) DEFAULT NULL,
  `rgData` json DEFAULT NULL,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `handle` (`handle`),
  UNIQUE KEY `uq_rb_profile_handle` (`handle`),
  CONSTRAINT `fk_profile_user` FOREIGN KEY (`user_id`) REFERENCES `rb_user` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- rb_vcard_share ----
CREATE TABLE `rb_vcard_share` (
  `share_id` bigint NOT NULL AUTO_INCREMENT,
  `vcard_id` bigint NOT NULL,
  `owner_user_id` bigint NOT NULL,
  `target_user_id` bigint DEFAULT NULL,
  `target_email` varchar(200) DEFAULT NULL,
  `share_token` varchar(64) NOT NULL,
  `is_public` tinyint(1) NOT NULL DEFAULT '0',
  `is_archived` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`share_id`),
  UNIQUE KEY `uq_rb_vcard_share_token` (`share_token`),
  KEY `idx_rb_vcard_share_vcard` (`vcard_id`),
  KEY `idx_rb_vcard_share_owner` (`owner_user_id`),
  KEY `idx_rb_vcard_share_target_user` (`target_user_id`),
  KEY `idx_rb_vcard_share_target_email` (`target_email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
