"""
Dump all tables to two files: <name>.sql (DDL only) and <name>.data (INSERTs only).
Prompts for a base name (default: db_dump).
"""
from __future__ import annotations

import datetime
import json
from decimal import Decimal
from pathlib import Path

from sqlalchemy import text

from app import create_app
from extensions import db


def _escape(val):
    """Render a Python value as a MySQL-friendly SQL literal."""
    if val is None:
        return "NULL"
    if isinstance(val, bool):
        return "1" if val else "0"
    if isinstance(val, (int, float, Decimal)):
        return str(val)
    if isinstance(val, datetime.datetime):
        return f"'{val.isoformat(sep=' ', timespec='seconds')}'"
    if isinstance(val, datetime.date):
        return f"'{val.isoformat()}'"
    if isinstance(val, (dict, list)):
        val = json.dumps(val, ensure_ascii=False)
    s = str(val)
    s = s.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{s}'"


def _base_paths(name: str) -> tuple[Path, Path]:
    """Return (schema_path, data_path) using a base name/path and fixed suffixes."""
    base = Path(name)
    base_no_ext = base.with_suffix("") if base.suffix else base
    return base_no_ext.with_suffix(".sql"), base_no_ext.with_suffix(".data")


def dump_all(base_name: str):
    app = create_app()
    with app.app_context():
        engine = db.engine
        with engine.connect() as conn:
            tables = [row[0] for row in conn.execute(text("SHOW TABLES")).fetchall()]

            schema_path, data_path = _base_paths(base_name)

            # Write schema (DDL only)
            with schema_path.open("w", encoding="utf-8") as f_schema:
                f_schema.write("-- Database schema dump (DDL only) generated by dump_db.py\n")
                for tbl in tables:
                    f_schema.write(f"\n-- ---- {tbl} ----\n")
                    create_row = conn.execute(text(f"SHOW CREATE TABLE `{tbl}`")).fetchone()
                    ddl = create_row[1] if create_row else ""
                    f_schema.write(f"{ddl};\n")

            # Write data (INSERTs only)
            with data_path.open("w", encoding="utf-8") as f_data:
                f_data.write("-- Database data dump (INSERTs only) generated by dump_db.py\n")
                f_data.write("SET FOREIGN_KEY_CHECKS=0;\n")

                for tbl in tables:
                    rows = conn.execute(text(f"SELECT * FROM `{tbl}`")).fetchall()
                    if not rows:
                        continue
                    f_data.write(f"\n-- ---- {tbl} ----\n")
                    first_map = rows[0]._mapping
                    cols = list(first_map.keys())
                    col_list = ", ".join(f"`{c}`" for c in cols)
                    f_data.write(f"INSERT INTO `{tbl}` ({col_list}) VALUES\n")

                    vals_lines = []
                    for r in rows:
                        rm = r._mapping
                        vals = [_escape(rm[c]) for c in cols]
                        vals_lines.append("(" + ", ".join(vals) + ")")
                    f_data.write(",\n".join(vals_lines) + ";\n")

                f_data.write("\nSET FOREIGN_KEY_CHECKS=1;\n")

            return schema_path, data_path


if __name__ == "__main__":
    base = input("Output base name [db_dump]: ").strip() or "db_dump"
    schema_path, data_path = dump_all(base)
    print(f"Schema written to: {schema_path.resolve()}")
    print(f"Data written to:   {data_path.resolve()}")
