"""
Dump all tables (DDL + data) from the configured database into a single SQL file.
Prompts for an output file name (default: db_dump.sql).
"""
from __future__ import annotations

import datetime
import json
from decimal import Decimal
from pathlib import Path

from sqlalchemy import text

from app import create_app
from extensions import db


def _escape(val):
    """Render a Python value as a MySQL-friendly SQL literal."""
    if val is None:
        return "NULL"
    if isinstance(val, bool):
        return "1" if val else "0"
    if isinstance(val, (int, float, Decimal)):
        return str(val)
    if isinstance(val, datetime.datetime):
        return f"'{val.isoformat(sep=' ', timespec='seconds')}'"
    if isinstance(val, datetime.date):
        return f"'{val.isoformat()}'"
    if isinstance(val, (dict, list)):
        val = json.dumps(val, ensure_ascii=False)
    s = str(val)
    s = s.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{s}'"


def dump_all(out_path: Path):
    app = create_app()
    with app.app_context():
        engine = db.engine
        with engine.connect() as conn:
            tables = [row[0] for row in conn.execute(text("SHOW TABLES")).fetchall()]

            with out_path.open("w", encoding="utf-8") as f:
                f.write("-- Database dump generated by dump_db.py\n")
                f.write("-- Includes CREATE TABLE and INSERT statements for all tables\n\n")
                f.write("SET FOREIGN_KEY_CHECKS=0;\n")

                for tbl in tables:
                    f.write(f"\n-- ---- {tbl} ----\n")

                    create_row = conn.execute(text(f"SHOW CREATE TABLE `{tbl}`")).fetchone()
                    ddl = create_row[1] if create_row else ""
                    f.write(f"{ddl};\n")

                    rows = conn.execute(text(f"SELECT * FROM `{tbl}`")).fetchall()
                    if not rows:
                        continue

                    first_map = rows[0]._mapping
                    cols = list(first_map.keys())
                    col_list = ", ".join(f"`{c}`" for c in cols)
                    f.write(f"INSERT INTO `{tbl}` ({col_list}) VALUES\n")

                    vals_lines = []
                    for r in rows:
                        rm = r._mapping
                        vals = [_escape(rm[c]) for c in cols]
                        vals_lines.append("(" + ", ".join(vals) + ")")
                    f.write(",\n".join(vals_lines) + ";\n")

                f.write("\nSET FOREIGN_KEY_CHECKS=1;\n")


if __name__ == "__main__":
    fname = input("Output SQL file name [db_dump.sql]: ").strip() or "db_dump.sql"
    path = Path(fname)
    dump_all(path)
    print(f"Dump written to: {path.resolve()}")
