-- Database dump generated by dump_db.py
-- Includes CREATE TABLE and INSERT statements for all tables

SET FOREIGN_KEY_CHECKS=0;

-- ---- alembic_version ----
CREATE TABLE `alembic_version` (
  `version_num` varchar(32) NOT NULL,
  PRIMARY KEY (`version_num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
