"""release1 schema

Revision ID: 1256eb79eccf
Revises: 
Create Date: 2025-12-25 19:05:53.512789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1256eb79eccf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rb_audit',
    sa.Column('audit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('tblname', sa.String(length=64), nullable=False),
    sa.Column('row_id', sa.BigInteger(), nullable=False),
    sa.Column('audit_date', sa.DateTime(), nullable=False),
    sa.Column('action', sa.Enum('add', 'invite', 'register', 'login', 'edit'), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.Enum('self', 'admin', 'api'), nullable=False),
    sa.Column('prev_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_rb_audit_event_id'), 'rb_audit', ['event_id'], unique=False)
    op.create_table('rb_user',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('invited', 'active', 'blocked', 'deleted'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.Column('invited_by', sa.BigInteger(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_rb_user_email'), 'rb_user', ['email'], unique=True)
    op.create_index(op.f('ix_rb_user_status'), 'rb_user', ['status'], unique=False)
    op.create_table('rb_user_profile',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rgDisplay', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('rgData', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['rb_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_index('user_code', table_name='todo')
    op.drop_table('todo')
    op.drop_table('chat_message')
    op.drop_index('code', table_name='vemp')
    op.drop_index('idx_user_cv_user_id', table_name='vemp')
    op.drop_table('vemp')
    op.drop_table('profcv')
    op.drop_index('uk_chat_topic_name', table_name='chat_topic')
    op.drop_table('chat_topic')
    op.drop_index('key1', table_name='tblbank')
    op.drop_table('tblbank')
    op.drop_table('project')
    op.drop_table('task')
    op.drop_table('notes')
    op.drop_table('chat_topic_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_topic_user',
    sa.Column('topic_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vcpid', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('joined_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['chat_topic.id'], name='chat_topic_user_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vcpid'], ['vemp.vcpid'], name='fk_chat_user_vcpid', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'vcpid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('notes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('task',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('team', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='task_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('project',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tblbank',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ac', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('vdate', sa.DATE(), nullable=True),
    sa.Column('tdate', sa.DATE(), nullable=True),
    sa.Column('tdesc', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('dc', mysql.VARCHAR(length=1), nullable=True),
    sa.Column('amt', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('remark', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('edate', sa.DATE(), nullable=True),
    sa.Column('txnline', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('key1', 'tblbank', ['ac', 'vdate', 'tdate', 'tdesc', 'dc', 'amt'], unique=True)
    op.create_table('chat_topic',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by_vcpid', mysql.VARCHAR(length=6), nullable=True),
    sa.ForeignKeyConstraint(['created_by_vcpid'], ['vemp.vcpid'], name='fk_chat_topic_created_by_vcpid', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uk_chat_topic_name', 'chat_topic', ['name'], unique=True)
    op.create_table('profcv',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vcpid', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('pf_typ', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pf_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pf_data', mysql.LONGTEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vemp',
    sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vcpid', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('fullname', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('cvxml', mysql.TEXT(), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pin_hash', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('reset_token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('reset_token_expires_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_role', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_cv_user_id', 'vemp', ['user_id'], unique=True)
    op.create_index('code', 'vemp', ['vcpid'], unique=True)
    op.create_table('chat_message',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('sent_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('sender_vcpid', mysql.VARCHAR(length=6), nullable=True),
    sa.ForeignKeyConstraint(['sender_vcpid'], ['vemp.vcpid'], name='fk_chat_message_sender_vcpid', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['chat_topic.id'], name='chat_message_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('todo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vcpid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=6), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), server_default=sa.text("'Pending'"), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_code', 'todo', ['vcpid'], unique=False)
    op.drop_table('rb_user_profile')
    op.drop_index(op.f('ix_rb_user_status'), table_name='rb_user')
    op.drop_index(op.f('ix_rb_user_email'), table_name='rb_user')
    op.drop_table('rb_user')
    op.drop_index(op.f('ix_rb_audit_event_id'), table_name='rb_audit')
    op.drop_table('rb_audit')
    # ### end Alembic commands ###
